name: Build and test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout REPO Code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: cd webapp && yarn install
      - name: Lint code
        run: cd webapp && yarn lint
      - name: Inloggen op DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Bouw en push de Dockerimage naar DockerHUB
        uses: docker/build-push-action@v2
        with:
          context: ./webapp
          file: ./webapp/Dockerfile
          tags: desmeteliasondockerhub/webapp:latest
          push: true
