---
name: Build and test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: cd webapp && yarn install
      - name: Lint code
        run: cd webapp && yarn lint
      - name: Bouw de Dockerimage (niet vanaf DockerHUB)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          load: true
          tags: desmeteliasondockerhub/webapp:latest

